// Auto-generated by: pnpm db:types
// Run `pnpm db:types` after applying migrations to regenerate from your live Supabase schema.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      articles: {
        Row: {
          id: string;
          site_id: string | null;
          slug: string;
          url: string;
          title: string;
          meta_title: string | null;
          meta_description: string | null;
          schema_type: string | null;
          tldr_bullets: string[] | null;
          author_name: string | null;
          author_credential: string | null;
          body_md: string | null;
          body_html: string | null;
          primary_keyword: string | null;
          secondary_keywords: string[] | null;
          featured_image_url: string | null;
          faq_json_ld: Json | null;
          generation_scores_jsonb: Json | null;
          footnote_count: number | null;
          table_count: number | null;
          quote_count: number | null;
          version: number | null;
          status: string;
          published_at: string | null;
          updated_at: string | null;
          indexing_jobs_jsonb: Json | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          site_id?: string | null;
          slug: string;
          url: string;
          title: string;
          meta_title?: string | null;
          meta_description?: string | null;
          schema_type?: string | null;
          tldr_bullets?: string[] | null;
          author_name?: string | null;
          author_credential?: string | null;
          body_md?: string | null;
          body_html?: string | null;
          primary_keyword?: string | null;
          secondary_keywords?: string[] | null;
          featured_image_url?: string | null;
          faq_json_ld?: Json | null;
          generation_scores_jsonb?: Json | null;
          footnote_count?: number | null;
          table_count?: number | null;
          quote_count?: number | null;
          version?: number | null;
          status?: string;
          published_at?: string | null;
          updated_at?: string | null;
          indexing_jobs_jsonb?: Json | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string | null;
          slug?: string;
          url?: string;
          title?: string;
          meta_title?: string | null;
          meta_description?: string | null;
          schema_type?: string | null;
          tldr_bullets?: string[] | null;
          author_name?: string | null;
          author_credential?: string | null;
          body_md?: string | null;
          body_html?: string | null;
          primary_keyword?: string | null;
          secondary_keywords?: string[] | null;
          featured_image_url?: string | null;
          faq_json_ld?: Json | null;
          generation_scores_jsonb?: Json | null;
          footnote_count?: number | null;
          table_count?: number | null;
          quote_count?: number | null;
          version?: number | null;
          status?: string;
          published_at?: string | null;
          updated_at?: string | null;
          indexing_jobs_jsonb?: Json | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      sites: {
        Row: {
          id: string;
          name: string;
          domain: string;
          supabase_config_jsonb: Json | null;
          vercel_config_jsonb: Json | null;
          indexing_adapters: string[] | null;
          brand_voice: string | null;
          structure_template_jsonb: Json | null;
          default_author_jsonb: Json | null;
          notification_config_jsonb: Json | null;
          approval_config_jsonb: Json | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          domain: string;
          supabase_config_jsonb?: Json | null;
          vercel_config_jsonb?: Json | null;
          indexing_adapters?: string[] | null;
          brand_voice?: string | null;
          structure_template_jsonb?: Json | null;
          default_author_jsonb?: Json | null;
          notification_config_jsonb?: Json | null;
          approval_config_jsonb?: Json | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          domain?: string;
          supabase_config_jsonb?: Json | null;
          vercel_config_jsonb?: Json | null;
          indexing_adapters?: string[] | null;
          brand_voice?: string | null;
          structure_template_jsonb?: Json | null;
          default_author_jsonb?: Json | null;
          notification_config_jsonb?: Json | null;
          approval_config_jsonb?: Json | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      keyword_clusters: {
        Row: {
          id: string;
          site_id: string | null;
          primary_keyword: string;
          related_keywords: string[] | null;
          priority: number | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          site_id?: string | null;
          primary_keyword: string;
          related_keywords?: string[] | null;
          priority?: number | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string | null;
          primary_keyword?: string;
          related_keywords?: string[] | null;
          priority?: number | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      topic_candidates: {
        Row: {
          id: string;
          site_id: string | null;
          headline: string;
          sources_jsonb: Json | null;
          score: number | null;
          status: string;
          discovered_at: string | null;
        };
        Insert: {
          id?: string;
          site_id?: string | null;
          headline: string;
          sources_jsonb?: Json | null;
          score?: number | null;
          status?: string;
          discovered_at?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string | null;
          headline?: string;
          sources_jsonb?: Json | null;
          score?: number | null;
          status?: string;
          discovered_at?: string | null;
        };
        Relationships: [];
      };
      source_scrapes: {
        Row: {
          id: string;
          url: string;
          url_hash: string;
          content_md: string;
          source_domain: string;
          authority_score: number | null;
          scraped_at: string | null;
          expires_at: string;
        };
        Insert: {
          id?: string;
          url: string;
          url_hash: string;
          content_md: string;
          source_domain: string;
          authority_score?: number | null;
          scraped_at?: string | null;
          expires_at: string;
        };
        Update: {
          id?: string;
          url?: string;
          url_hash?: string;
          content_md?: string;
          source_domain?: string;
          authority_score?: number | null;
          scraped_at?: string | null;
          expires_at?: string;
        };
        Relationships: [];
      };
      revisions: {
        Row: {
          id: string;
          article_id: string | null;
          version: number;
          body_md: string;
          editor_scores_jsonb: Json | null;
          editor_notes: string | null;
          source_type: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          article_id?: string | null;
          version: number;
          body_md: string;
          editor_scores_jsonb?: Json | null;
          editor_notes?: string | null;
          source_type?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          article_id?: string | null;
          version?: number;
          body_md?: string;
          editor_scores_jsonb?: Json | null;
          editor_notes?: string | null;
          source_type?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      assessments: {
        Row: {
          id: string;
          article_id: string | null;
          week_of: string;
          gsc_data_jsonb: Json | null;
          ga4_data_jsonb: Json | null;
          serp_positions_jsonb: Json | null;
          ai_citations_jsonb: Json | null;
          recommendations_jsonb: Json | null;
          batch_request_id: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          article_id?: string | null;
          week_of: string;
          gsc_data_jsonb?: Json | null;
          ga4_data_jsonb?: Json | null;
          serp_positions_jsonb?: Json | null;
          ai_citations_jsonb?: Json | null;
          recommendations_jsonb?: Json | null;
          batch_request_id?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          article_id?: string | null;
          week_of?: string;
          gsc_data_jsonb?: Json | null;
          ga4_data_jsonb?: Json | null;
          serp_positions_jsonb?: Json | null;
          ai_citations_jsonb?: Json | null;
          recommendations_jsonb?: Json | null;
          batch_request_id?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      improvements: {
        Row: {
          id: string;
          article_id: string | null;
          assessment_id: string | null;
          proposed_changes_jsonb: Json;
          gemini_review_jsonb: Json | null;
          expected_impact: string | null;
          estimated_position_gain: number | null;
          article_version_at_proposal: number;
          status: string;
          approval_token: string | null;
          approval_expires_at: string | null;
          approved_by: string | null;
          approved_at: string | null;
          approval_channel: string | null;
          rejection_reason: string | null;
          applied_at: string | null;
          rollback_revision_id: string | null;
          inngest_run_id: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          article_id?: string | null;
          assessment_id?: string | null;
          proposed_changes_jsonb: Json;
          gemini_review_jsonb?: Json | null;
          expected_impact?: string | null;
          estimated_position_gain?: number | null;
          article_version_at_proposal: number;
          status?: string;
          approval_token?: string | null;
          approval_expires_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          approval_channel?: string | null;
          rejection_reason?: string | null;
          applied_at?: string | null;
          rollback_revision_id?: string | null;
          inngest_run_id?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          article_id?: string | null;
          assessment_id?: string | null;
          proposed_changes_jsonb?: Json;
          gemini_review_jsonb?: Json | null;
          expected_impact?: string | null;
          estimated_position_gain?: number | null;
          article_version_at_proposal?: number;
          status?: string;
          approval_token?: string | null;
          approval_expires_at?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          approval_channel?: string | null;
          rejection_reason?: string | null;
          applied_at?: string | null;
          rollback_revision_id?: string | null;
          inngest_run_id?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      consumed_approval_tokens: {
        Row: {
          token: string;
          used_at: string;
        };
        Insert: {
          token: string;
          used_at?: string;
        };
        Update: {
          token?: string;
          used_at?: string;
        };
        Relationships: [];
      };
      api_batch_logs: {
        Row: {
          id: string;
          service: string;
          batch_size: number;
          request_at: string | null;
          response_time_ms: number | null;
          cost_estimate: number | null;
        };
        Insert: {
          id?: string;
          service: string;
          batch_size?: number;
          request_at?: string | null;
          response_time_ms?: number | null;
          cost_estimate?: number | null;
        };
        Update: {
          id?: string;
          service?: string;
          batch_size?: number;
          request_at?: string | null;
          response_time_ms?: number | null;
          cost_estimate?: number | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
