-- Articles table with v1.5 meta columns
CREATE TABLE articles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id uuid REFERENCES sites(id) ON DELETE CASCADE,
  slug text NOT NULL,
  url text NOT NULL,
  title text NOT NULL,
  meta_title text,
  meta_description text,
  schema_type text,
  tldr_bullets text[] DEFAULT '{}',
  author_name text,
  author_credential text,
  body_md text,
  body_html text,
  primary_keyword text,
  secondary_keywords text[] DEFAULT '{}',
  featured_image_url text,
  faq_json_ld jsonb,
  generation_scores_jsonb jsonb,
  footnote_count int DEFAULT 0,
  table_count int DEFAULT 0,
  quote_count int DEFAULT 0,
  version int DEFAULT 1,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  published_at timestamptz,
  updated_at timestamptz DEFAULT now(),
  indexing_jobs_jsonb jsonb DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  UNIQUE(site_id, slug)
);
